load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "binary_search",
    srcs = [ "binary_search.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "e1-2-1",
    srcs = [ "exercises/e1-2-1.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "flips",
    srcs = [ "flips.cpp" ],
    deps = [ "//lib:lib" ],
)