load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test-digraph",
    srcs = [ "test-digraph.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "test-symbol-digraph",
    srcs = [ "test-symbol-digraph.cpp" ],
    deps = [ "//lib:lib" ],
)