load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test-cc",
    srcs = [ "test-cc.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "test-cycle",
    srcs = [ "test-cycle.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "test-graph",
    srcs = [ "test-graph.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "test-paths",
    srcs = [ "test-paths.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "test-search",
    srcs = [ "test-search.cpp" ],
    deps = [ "//lib:lib" ],
)

cc_binary(
    name = "test-symbol-graph",
    srcs = [ "test-symbol-graph.cpp" ],
    deps = [ "//lib:lib" ],
)
